services:
  - type: web
    name: onboarding-portal
    runtime: node
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: onboarding-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/health

databases:
  - name: onboarding-db
    databaseName: onboarding_portal
    user: onboarding_user
    plan: free